title: Xcode Project Manager
email: pepibumur@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Xcode Project Manager is a command line tool that helps you use Xcode
  at a large scale. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xcodepm.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xcodepm
github_username:  xcode-project-manager

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed